version: 2
updates:
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "03:00"
    timezone: "Asia/Singapore"
  open-pull-requests-limit: 99
  reviewers:
  - samhamilton
