application: universal-helix-585
version: 1
runtime: python
api_version: 1
threadsafe: true

handlers:
# index files
- url: /(.*)/
  static_files: public/\1/index.html
  upload: public/(.*)/index.html
  expiration: "15m"

# site root
- url: /
  static_files: public/index.html
  upload: public/index.html
  expiration: "15m"

- url: /blog/(.*)
  static_files: public/blog/\1/index.html
  upload: public/blog/(.*)/index.html
  expiration: "15m"

- url: /
  static_dir: public