menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId: UA-4507040-7
